### ISSUE TITLE
What does the asterisk mean?

### ISSUE THREAD

**Issue by protist** [andrewgregory/pacreport#1]
Hi, thanks for the program. It's super useful! Could you please tell me what the asterisk means? I can't see it documented anywhere. For example:
```
$ pacreport
Unneeded Packages Installed Explicitly:
  airsonic                	237.71 M - A free, web-based media streamer and jukebox.
 *apache                  	  5.21 M - A high performance Unix-based HTTP server
  autoconf                	  2.20 M - A GNU tool for automatically configuring source code (base-devel)
  automake                	  1.57 M - A GNU tool for automatically creating Makefiles (base-devel)
  backintime-cli          	  1.54 M - Simple backup system inspired from the Flyback Project and TimeVault. CLI version.
  bison                   	  2.31 M - The GNU general-purpose parser generator (base-devel)
 *certbot-apache          	 12.15 M - Apache plugin for Let’s Encrypt client
...
```
Why are `apache` and `certbot-apache` asterisked?

**Comment by andrewgregory** [comment]
`man pacreport`

> Packages prefixed by an asterisk ("*") are optional dependencies for another package.

**Comment by protist** [comment]
Oops, sorry, for some reason I didn't think there was a manual included. I even checked the [front page](https://github.com/andrewgregory/pacreport), which is `man`-esque in format, but couldn't see it there either. Thank you @andrewgregory.

**Comment by andrewgregory** [comment]
This is actually the wrong project. It was superseded by pacutils some
time ago.  You want https://github.com/andrewgregory/pacutils/blob/master/doc/pacreport.pod

**Comment by protist** [comment]
Ah got it. Thanks again.
